# Generated by Django 4.1.1 on 2022-09-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('casa', models.IntegerField()),
                ('ponto_ref', models.CharField(max_length=300)),
            ],
        ),
    ]
